language: ruby
rvm:
  - 2.2
before_install:
  - openssl aes-256-cbc -K $encrypted_4fddfda5b09c_key -iv $encrypted_4fddfda5b09c_iv -in deploy_key.enc -out deploy_key -d
  - gem install bundler
  - chmod 600 deploy_key
  - mv deploy_key ~/.ssh/id_rsa
  - git config --global user.email "xcatliu@gmail.com"
  - git config --global user.name "xcatliu"
script:
  - bundle exec rake site:publish