markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
repository: https://github.com/jekyll/jekyll
help_url: https://github.com/jekyll/jekyll-help
google_analytics_id: UA-45256157-1
timezone: America/Los_Angeles
